/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author idea
 */
public class Giris extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Giris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BölümEkle = new javax.swing.JButton();
        PersonelTablosu = new javax.swing.JButton();
        PersonelEkle = new javax.swing.JButton();
        BolumTablosu = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));

        BölümEkle.setText("Bölüm Ekle");
        BölümEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BölümEkleActionPerformed(evt);
            }
        });

        PersonelTablosu.setText("Personel Tablosu");
        PersonelTablosu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonelTablosuActionPerformed(evt);
            }
        });

        PersonelEkle.setText("Personel Ekle");
        PersonelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonelEkleActionPerformed(evt);
            }
        });

        BolumTablosu.setText("Bölüm Tablosu");
        BolumTablosu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolumTablosuActionPerformed(evt);
            }
        });

        jButton6.setText("Personel Tablosundan Eleman Sil");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BolumTablosu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BölümEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PersonelTablosu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PersonelEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BölümEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BolumTablosu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonelTablosu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//sadece 1 tane getiriyor
    private void BölümEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BölümEkleActionPerformed
        
        
        BolumEkle bEkle=new BolumEkle();
        bEkle.setVisible(true);
       
            
        
    }//GEN-LAST:event_BölümEkleActionPerformed

    private void PersonelTablosuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonelTablosuActionPerformed

        Baglanti bag=new Baglanti();
        String ekle="";
        bag.baglanti();
        PersoneTablosu pTablo=new PersoneTablosu();
        pTablo.setVisible(true);
        try {   
            PreparedStatement stat=bag.c.prepareStatement("select * from personel");
            ResultSet Rs=stat.executeQuery();
            while(Rs.next()){
               ekle=ekle+Rs.getInt(1)+"   "+Rs.getString(2)+"   "+Rs.getString(3)+"   "+Rs.getString(4)+"   "+Rs.getLong(5)+"   "+Rs.getString(6)+"   "+Rs.getInt(7)+"\n";
               pTablo.PersonelListesi.setText(ekle);
               pTablo.setVisible(true);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        bag.bagKapat();
        
        
    }//GEN-LAST:event_PersonelTablosuActionPerformed

    private void PersonelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonelEkleActionPerformed
        PersonelEkle pEkle=new PersonelEkle();
        pEkle.setVisible(true);
        
        
    }//GEN-LAST:event_PersonelEkleActionPerformed

    private void BolumTablosuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolumTablosuActionPerformed
        
        Baglanti bag=new Baglanti();
        String ekle="";
        bag.baglanti();
        BolumTablosu bTbablo=new BolumTablosu();
        bTbablo.setVisible(true);
        try {   
            PreparedStatement stat=bag.c.prepareStatement("select * from bolum");
            ResultSet Rs=stat.executeQuery();
            while(Rs.next()){
               ekle = ekle+Rs.getInt(1)+"   "+Rs.getString(2)+"   "+Rs.getString(3)+"\n";
              // bTbablo.BolumListesi.setText(ekle);
               bTbablo.setVisible(true);
            }
            bTbablo.BolumListesi.setText(ekle);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        bag.bagKapat();
        
    }//GEN-LAST:event_BolumTablosuActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        PersonelTablosundanSilme VeriSil=new PersonelTablosundanSilme();
        VeriSil.setVisible(true);
                
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BolumTablosu;
    private javax.swing.JButton BölümEkle;
    private javax.swing.JButton PersonelEkle;
    private javax.swing.JButton PersonelTablosu;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
